name: Build ZMK firmware

on:
  push:
    paths:
      - config/**
      - .github/workflows/build-user-config.yml
      - west.yml
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_file: build.yaml
